// <auto-generated />
using System;
using McpManager.Core.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace McpManager.Core.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260623120000_AddMcpServerToolPrefix")]
    partial class AddMcpServerToolPrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ApiKeyMcpNamespace", b =>
                {
                    b.Property<Guid>("AllowedNamespacesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeysId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedNamespacesId", "ApiKeysId");

                    b.HasIndex("ApiKeysId");

                    b.ToTable("ApiKeyNamespaces", (string)null);
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.ApiKeys.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpConnectionTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("McpRetryAttempts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            McpConnectionTimeoutSeconds = 120,
                            McpRetryAttempts = 3
                        });
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GivenName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SidebarCollapsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000001-0000-0000-0000-000000000000"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d979655-fed0-411b-b2ad-66345adceab3",
                            CreationTime = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@mcpmanager.local",
                            EmailConfirmed = true,
                            GivenName = "Daniel",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@MCPMANAGER.LOCAL",
                            NormalizedUserName = "ADMIN@MCPMANAGER.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEOqOiuA0bHdat2FXMTttZDTVksgYKQ9t5Pzc92oGjnNRcGUSiPUQOM00wFjo1eeblQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "U7LXVLANYGF3IKRETLA5YF4SJ4Z3FEA3",
                            SidebarCollapsed = false,
                            Surname = "Oliveira",
                            Theme = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin@mcpmanager.local"
                        });
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Admin",
                            ClaimValue = "Admin",
                            UserId = new Guid("00000001-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RateLimitEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateLimitRequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateLimitStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("McpNamespaces");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespaceServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("McpNamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId");

                    b.HasIndex("McpNamespaceId", "McpServerId")
                        .IsUnique();

                    b.ToTable("McpNamespaceServers");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespaceTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescriptionOverride")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("McpNamespaceServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpToolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameOverride")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("McpToolId");

                    b.HasIndex("McpNamespaceServerId", "McpToolId")
                        .IsUnique();

                    b.ToTable("McpNamespaceTools");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Arguments")
                        .HasColumnType("TEXT");

                    b.Property<string>("Command")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnvironmentVariables")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenApiSpecification")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToolPrefix")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransportType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Uri")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("McpServers");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpServerLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId", "CreationTime");

                    b.ToTable("McpServerLogs");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomInputSchema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSchema")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalRequests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("McpServerId", "Name")
                        .IsUnique();

                    b.ToTable("McpTools");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpToolRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExecutionTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("McpNamespaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("McpToolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("McpNamespaceId");

                    b.HasIndex("McpToolId");

                    b.ToTable("McpToolRequests");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreationTime");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("ApiKeyMcpNamespace", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpNamespace", null)
                        .WithMany()
                        .HasForeignKey("AllowedNamespacesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McpManager.Core.Data.Models.ApiKeys.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeysId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.RoleClaim", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserClaim", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Identity.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserLogin", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Identity.User", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserRole", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Identity.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McpManager.Core.Data.Models.Identity.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.UserToken", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Identity.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespaceServer", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpNamespace", "McpNamespace")
                        .WithMany("Servers")
                        .HasForeignKey("McpNamespaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpServer", "McpServer")
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpNamespace");

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespaceTool", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpNamespaceServer", "McpNamespaceServer")
                        .WithMany("Tools")
                        .HasForeignKey("McpNamespaceServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpTool", "McpTool")
                        .WithMany()
                        .HasForeignKey("McpToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpNamespaceServer");

                    b.Navigation("McpTool");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpServer", b =>
                {
                    b.OwnsOne("McpManager.Core.Data.Models.Authentication.Auth", "Auth", b1 =>
                        {
                            b1.Property<Guid>("McpServerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApiKeyName")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ApiKeyValue")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientId")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.Property<string>("ClientSecret")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Password")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Scope")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Token")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TokenEndpoint")
                                .HasMaxLength(2000)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Username")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT");

                            b1.HasKey("McpServerId");

                            b1.ToTable("McpServers");

                            b1.WithOwner()
                                .HasForeignKey("McpServerId");
                        });

                    b.Navigation("Auth")
                        .IsRequired();
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpServerLog", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpServer", "McpServer")
                        .WithMany()
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpTool", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpServer", "McpServer")
                        .WithMany("Tools")
                        .HasForeignKey("McpServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpServer");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpToolRequest", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpNamespace", "McpNamespace")
                        .WithMany()
                        .HasForeignKey("McpNamespaceId");

                    b.HasOne("McpManager.Core.Data.Models.Mcp.McpTool", "McpTool")
                        .WithMany()
                        .HasForeignKey("McpToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("McpNamespace");

                    b.Navigation("McpTool");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Notifications.Notification", b =>
                {
                    b.HasOne("McpManager.Core.Data.Models.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Identity.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Logins");

                    b.Navigation("Roles");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespace", b =>
                {
                    b.Navigation("Servers");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpNamespaceServer", b =>
                {
                    b.Navigation("Tools");
                });

            modelBuilder.Entity("McpManager.Core.Data.Models.Mcp.McpServer", b =>
                {
                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
